### ISSUE TITLE
Calibre throws an error saying the plugin is invalid

### ISSUE THREAD

**Issue by Jemeni11** [Mikowmer/FicHub2Calibre#1]
I get this error when I try to install [FicHub2Calibre](https://github.com/Mikowmer/FicHub2Calibre/releases/download/v0.0.1-alpha/FicHub2Calibre-v0.0.1.zip) 

![bug](https://user-images.githubusercontent.com/52603291/226180621-eead5936-9070-42d5-b93a-b078b219c6d6.png)

Apparently, plugins need a top-level `__init__.py` file.

EDIT: I opened the zip and the top level `__init__.py` is there so I have no idea why I am getting this error. I have installed plugins before and they have worked.
EDIT2: Calibre Version 6.14
EDIT3: Error message
```sh
calibre, version 6.14.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 
'/home/nonso/Downloads/FicHub2Calibre-v0.0.1.zip' is 
invalid. It does not contain a top-level __init__.py file

calibre 6.14  embedded-python: True
Linux-5.15.0-67-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.15.0-67-generic', '#74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Count Pages (1, 12, 1) && EpubMerge (2, 15, 0)
 && FanFicFare (4, 21, 0)

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/nonso/Downloads/FicHub2Calibre-v0.0.1.zip' 
is invalid. 

It does not contain a top-level __init__.py file

```

**Comment by Mikowmer** [comment]
Drat. See forum post here: https://www.mobileread.com/forums/showpost.php?p=4307628&postcount=4
> It is packaged wrong.
> Re-zip eliminating the fic2hub folder inside
> Everything is supposed to start at the Zip level

**Comment by Mikowmer** [comment]
And fixed. Thank you for bringing this to my attention!

**Comment by Jemeni11** [comment]
> And fixed. Thank you for bringing this to my attention!

Thanks. You're welcome :+1:
